# This module looks for environment variables detailing where LANDSFCUTIL lib is
# If variables are not set, LANDSFCUTIL will be built from external source 

if(DEFINED ENV{LANDSFCUTIL_LIB4} )
  set(LANDSFCUTIL_VER $ENV{LANDSFCUTIL_VER} CACHE STRING "LANDSFCUTIL Version")
  set(LANDSFCUTIL_LIB4 $ENV{LANDSFCUTIL_LIB4} CACHE STRING "LANDSFCUTIL_4 Library Location")
  set(LANDSFCUTIL_LIB8 $ENV{LANDSFCUTIL_LIBd} CACHE STRING "LANDSFCUTIL_8 Library Location")
  set(LANDSFCUTIL_LIBd $ENV{LANDSFCUTIL_LIBd} CACHE STRING "LANDSFCUTIL_d Library Location")
  set(LANDSFCUTIL_INC4 $ENV{LANDSFCUTIL_INC4} CACHE STRING "LANDSFCUTIL_4 Include Location")
  set(LANDSFCUTIL_INC8 $ENV{LANDSFCUTIL_INC8} CACHE STRING "LANDSFCUTIL_8 Include Location")
  set(LANDSFCUTIL_INCd $ENV{LANDSFCUTIL_INCd} CACHE STRING "LANDSFCUTIL_d Include Location")
endif()
